### ISSUE TITLE
Import data from GENEActiv device

### ISSUE THREAD

**Issue by andrectonon** [tscnlab/LightLogR#27]
Hi everyone,

Great job putting this package together. I am very excited to try it :)

My name is André Comiran Tonon, I am currently working with Dr Benicio Frey at McMaster University and leading the CAN-BIND actigraphy analyses. In all CAN-BIND studies, across multiple sites in Canada, we use the GENEActiv device. This package is a great opportunity for us to conduct multi-site light exposure analyses in our multi-site clinical trials.

GENEActiv relies on GGIR, an R package that pretty much handles data filtering and analysis in a lazy way. However, I managed to export the .csv files that contain 15min epoch data for light exposure. I could use that with LightLogR, I am guessing.

But it would definitely be easier and more practical to import the raw bin files from GENEActiv for such analyses. I would send attached an example of a raw bin file but the format is not supported. I could send it via email. Mine is andrectonon@gmail.com.

I'm happy to discuss this matter in more detail. Thank you so much in advance!

André

**Comment by JZauner** [comment]
Hi André,

to mirror our conversation via email, here are the main takeaways so far:

- Using the pre-processed data you provided with LightLogR functionality is quite straightforward. I have attached a small script that uses the RData file, prepares it for LightLogR, and does some small stuff like visualization and metric calculations with LightLogR functions.
[GENEActiv_Script.R.zip](https://github.com/user-attachments/files/16361623/GENEActiv_Script.R.zip)

- Follow-up thought: If the folder structure is always the same, it would be quite simple to write an import function, providing the path to the base folder, and all the rest is done by the function, making it "LightLogR-ready. “

-  Working with the original .bin file is not that easy and I am uncertain at this point if it is reasonably feasible to depend on manufacturers packages to read in the data, but am open to the discussion and suggestions.

Let us discuss this further and see how to tackle this best.
Johannes

**Comment by andrectonon** [comment]
This material is great, thank you!
Yes, the folder structure is always the same. When you analyze several bin files, they will all appear in the same folders. Raw data will be in the “meta” folders, all side by side. And data that was already processed will appear in the “results” folder as new lines in the same .csv files (for example, calculations of sleep onset, sleep duration etc etc).

Is there a way that we can import and analyze all RData files from the same folder at once?

Thanks!

André

From: Johannes Zauner ***@***.***>
Reply-To: tscnlab/LightLogR ***@***.***>
Date: Wednesday, July 24, 2024 at 7:50 AM
To: tscnlab/LightLogR ***@***.***>
Cc: André Tonon ***@***.***>, Author ***@***.***>
Subject: Re: [tscnlab/LightLogR] Import data from GENEActiv device (Issue #27)


Hi André,

to mirror our conversation via email, here are the main takeaways so far:

  *   Using the pre-processed data you provided with LightLogR functionality is quite straightforward. I have attached a small script that uses the RData file, prepares it for LightLogR, and does some small stuff like visualization and metric calculations with LightLogR functions.
GENEActiv_Script.R.zip<https://github.com/user-attachments/files/16361623/GENEActiv_Script.R.zip>
  *   Follow-up thought: If the folder structure is always the same, it would be quite simple to write an import function, providing the path to the base folder, and all the rest is done by the function, making it "LightLogR-ready. “
  *   Working with the original .bin file is not that easy and I am uncertain at this point if it is reasonably feasible to depend on manufacturers packages to read in the data, but am open to the discussion and suggestions.

Let us discuss this further and see how to tackle this best.
Johannes

**Comment by JZauner** [comment]
Hi André,

the import routine will go live with LightLogR 0.4.1. A pull request ist already in action, so it should go live in the next few days.

All the best,
Johannes
