### ISSUE TITLE
LLdata not found

### ISSUE THREAD

**Issue by dsherman11** [tscnlab/LightLogR#29]
Hi Johannes,

I'm having some trouble running LightLogR on a new Windows11 computer.  Most of it works fine, but there are some functions that seem to have trouble.  To test it out, I repeated the [README vignette](https://cran.r-project.org/web/packages/LightLogR/readme/README.html) and this line does not work:

> LLdata %>% gg_overview()
> **Error: object 'LLdata' not found**
> 

It worked last week on this same computer.  I did some maintenance on my widows file structure today, migrating to a new Windows user profile, so maybe this might have something to do with it.  However, all other R functions in the vignette seem to work as expected, both in the R console and in R Studio.  I even reinstalled Rtools in the new user profile, and then reinstalled LightLogR, but this did not help.

Perhaps some other clues: after starting R, activating the dplyr library results in the following:

> library(dplyr)
> Attaching package: ‘dplyr’
> **The following objects are masked from ‘package:stats’:
>     filter, lag
> The following objects are masked from ‘package:base’:
>     intersect, setdiff, setequal, union**

When trying "The whole game" vignette, the first set of commands results in:

> library(LightLogR)
> library(tidyverse)
── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ forcats   1.0.0     ✔ readr     2.1.5
✔ ggplot2   3.5.1     ✔ stringr   1.5.1
✔ lubridate 1.9.3     ✔ tibble    3.2.1
✔ purrr     1.0.2     ✔ tidyr     1.3.1
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
> library(gt)
> library(patchwork)

Any ideas about what might be causing this?  I'm new to R, so any help would be appreciated.   @JZauner

**Comment by JZauner** [comment]
Hi @dsherman11 ,

Thanks for reaching out! 
The example you are referring to is just an example of how to get the visualization. It must be used on a light exposure dataset you previously imported; thus, `LLdata` is just a stand-in. I will add a note to specify this, as the other examples in the Readme work via copy/paste, so I see how this could be misleading. 

However, you can directly test the functionality with the article on[ import & cleaning](https://tscnlab.github.io/LightLogR/articles/Import.html). 

I hope this helps. If you have any other troubles with the package or want new features, please get in touch with us!

All the best,
Johannes

**Comment by dsherman11** [comment]
Totally clear now!
Thanks for your response.
