### ISSUE TITLE
LightLogR with MotionWatch 8 

### ISSUE THREAD

**Issue by joanna-j99** [tscnlab/LightLogR#32]
Hi Johannes,
I am writing to you regarding the LightLogR package used for light exposure analysis. The team I work with would be very interested in using it to analyse our data, similar to what you present in the package description. During the experiment, we have been using a MotionWatch 8 devices (Camntech) but I do not see it in the list of supported devices. I wanted to ask if it is still possible to use LightLogR for our data, despite having different device? I am also uploading an example file.
I would very much appreciate your help! 
All the best,
Joanna

[sub02_test_1.csv](https://github.com/user-attachments/files/17029765/sub02_test_1.csv)

**Comment by JZauner** [comment]
Hi Joanna,

thanks for reaching out! I´ll gladly add the MotionWatch 8 to the list of supported devices. I can write an import function based on the file you provided. Two things I´d like to get a bit more detail on: 

- does the data always start at line 16 (i.e., column description at line 15), or does the header length depend on settings you make during export?
- is the time in the file local time or a fixed time zone (like UTC)?

All the best,
Johannes

**Comment by JZauner** [comment]
Hi Joanna,

the import routine will go live with LightLogR 0.4.1. A pull request ist already in action, so it should go live (on GitHub) in the next few days.

All the best,
Johannes
